import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  compilerOptions: {
    // Force runes mode for the project, except for libraries. Can be removed in svelte 6.
    runes: ({ filename }) => (filename.split(/[/\\]/).includes('node_modules') ? undefined : true)
  },
  kit: {
    // adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
    // If your environment is not supported, or you settled on a specific environment, switch out the adapter.
    // See https://svelte.dev/docs/kit/adapters for more information about adapters.
    adapter: adapter(),
    prerender: {
      handleHttpError: ({ path, referrer, message }) => {
        // Trip detail pages added in Phase 4
        if (/^\/travel\/.+/.exec(path)) {
          console.warn(`Prerender warning: ${message} (linked from ${referrer})`);
          return;
        }
        // /about added in Phase 5
        if (path.startsWith('/about')) {
          console.warn(`Prerender warning: ${message} (linked from ${referrer})`);
          return;
        }
        // Images are generated by the process-images script; safe to skip during build
        if (path.startsWith('/images/')) {
          return;
        }
        throw new Error(message);
      }
    }
  }
};

export default config;
